### ISSUE TITLE
Unable to trace ip - PHP Notice:  Trying to access array offset on value of type bool in /usr/share/IP-Tracer/modules/.traceip.php on line 28

### ISSUE THREAD

**Issue by kk0201** [rajkumardusad/IP-Tracer#41]
Install went smooth on Ubuntu 20.04 server, but getting error on php.

      _ ____    _
     (_)  _ \  | |_ _ __ __ _  ___ ___ _ __
     | | |_) | | __| '__/ _` |/ __/ _ \ '__|
     | |  __/  | |_| | | (_| | (_|  __/ |
     |_|_|      \__|_|  \__,_|\___\___|_|

   }----------------------------------------{
}--------------- IP Information ---------------{
   }----------------------------------------{

PHP Notice:  Trying to access array offset on value of type bool in /usr/share/IP-Tracer/modules/.traceip.php on line 28

 Sorry unable to track your IP Address !!!
 Check your Network connection !!
 If you are Online then check your IP Address !!

**Comment by rajkumardusad** [comment]
Try again we have fixed this issue.

**Comment by kk0201** [comment]
Thanks for fixing it, but it still doesn't work
      _ ____    _
     (_)  _ \  | |_ _ __ __ _  ___ ___ _ __
     | | |_) | | __| '__/ _` |/ __/ _ \ '__|
     | |  __/  | |_| | | (_| | (_|  __/ |
     |_|_|      \__|_|  \__,_|\___\___|_|


   }----------------------------------------{
}--------------- IP Information ---------------{
   }----------------------------------------{


 Sorry unable to track your IP Address !!!
 Check your Network connection !!
 If you are Online then check your IP Address !!

Linux:~$

**Comment by nurullah31** [comment]
Sorry unable to track your IP Address !!!
Check your Network connection !!
If you are Online then check your IP Address !!  ? ^^Why does not work

**Comment by zxcvfrtg** [comment]
Sorry unable to track your IP Address !!!
Check your Network connection !!
If you are Online then check your IP Address !! ? ^^Why does not work
